# This workflow uses actions that are not certified by GitHub.
name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-all-automation:
    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3
    
    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      
    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew web

      
      # Archive Test Result (Upload a Build Artifact, By: Action)
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with:
        name: Cucumber Report Uye
        path: reports
      
    # Deploy to Github Pages (Github Page Action, By: peaceiris)
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports
